schema_version: 2
project_id: prj_6741997c5c064e9d8f50be429f916ac8
name: workflow-labs
workflows:
- id: wf_ae6cd700
  directory: 도그푸딩--wf_ae6cd700
  name: 도그푸딩
  status: active
  created_at: 2026-08-01T14:32:43.441149+00:00
